# Generated by Django 6.0.3 on 2026-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_phone_number_marksreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['session_type', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='session_type',
            field=models.CharField(choices=[('partial', 'Partial exam'), ('first_final', 'First final exam'), ('second_final', 'Second final exam')], default='first_final', max_length=15),
        ),
    ]
