# Generated by Django 6.0.3 on 2026-04-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksreport',
            name='report_kind',
            field=models.CharField(choices=[('corrector', 'Corrector marks sheet'), ('final_average', 'Final average sheet')], default='corrector', max_length=20),
        ),
    ]
