# Generated by Django 6.0.4 on 2026-04-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_level'),
        ('core', '0010_marksreport_report_kind'),
    ]

    operations = [
    ]
