# Generated by Django 6.0.4 on 2026-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260430_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='second_round_complete',
            field=models.BooleanField(default=False),
        ),
    ]
